### ISSUE TITLE
add support for language specific fonts

### ISSUE THREAD

**Issue by sekthor** [sekthor/dnd-hugo#12]
- add fonts in `static`
- add css file with language classes, that set the respective fonts. something along the lines of
  ```css
  .elvish-script {
    src: url(/fonts/elvish.woff);
  }
  ```

using inline "unsafe" html we can do something like this in our markdown:

```html
The inscription of the gate said
<p class="elvish-script">
Speak friend and enter
</p>
```
